### PR TITLE
Rename to Stargaze

### LINKED ISSUE #207: Add CosmWasm support
🚀

### LINKED ISSUE #262: Add custom type for body hash
After removing custom decoding for posts, we also removed body hash. So it won't be meaningful until we add it back in via a custom protobuf type.

### LINKED ISSUE #266: The great rename
- [ ] rename repo
- [ ] rename in go.mod
- [ ] rename all imports
- [x] change address prefix to either `starts` or `s` (be sure not to conflict with Starname)
- [ ] change all scripts
- [ ] update CI

### LINKED ISSUE #278: STARS / CREDITS AMM
As a user, I would like to be able to purchase more CREDITS with STARS tokens if I run out or use more than my daily allotment of CREDITS. I should be able to purchase more CREDITS with STARS tokens.

Unlike my daily allocation of CREDITS, credits I purchase should NOT expire. See: https://github.com/public-awesome/stakebot/issues/266

We should setup some sort of Automated Market Maker for exchanging STARS for CREDITS.

Swapping CREDITS for STARS should incur a 5% fee to the community pool, see: https://discord.com/channels/755548171941445642/755564065794818089/800469061183602689

### PR DESCRIPTION
**Pull request by shanev**
Fixes #266. Fixes #262. Fixes #278. Fixes #207. 

Will rename Github repo as soon as this is merged in.

Expect something to break :)

TODO
- [ ] rename imports in stakewatcher
- [ ] rename imports in stakebot
- [ ] rename scripts on devnet machine

Notes
* Includes the B-Harvest / Tendermint liquidity module
* Adds CosmWasm 🚀

### CODE REVIEW

**Comment by jhernandezb** [comment]
Nice! I think needs .drone.yml signing, also would the binary remain the same `(staked)` ?

**Comment by shanev** [comment]
> Nice! I think needs .drone.yml signing, also would the binary remain the same `(staked)` ?

Renamed to `starsd`.

**Comment by JakeHartnell** [comment]
Looks good so far, testing locally to see how it plays with the backend...

**Comment by JakeHartnell** [comment]
Ok, this does break some things (as was to be expected).

First thing seems to be on the bot side (when an account is created):
```
INFO[0057] sending coins                                 address=stars15mdyz3cy5wu2lw8kk9nrp8em5e57ef4ctytvx0
2021/01/31 17:24:09 http: panic serving 127.0.0.1:35524: runtime error: invalid memory address or nil pointer dereference
goroutine 32 [running]:
net/http.(*conn).serve.func1(0xc001502140)
        /usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x15b9280, 0x259c320)
        /usr/local/go/src/runtime/panic.go:975 +0x47a
github.com/public-awesome/stakebot/bot.generateSubkey(0x1b752e0, 0xc000e7bb80, 0x0, 0xc000f97140, 0x2, 0x2, 0xc000ca7b00, 0xc001051020, 0x15, 0xc000f7d6f0, ...)
        /home/meow/Dev/Public-Awesome/stakebot/bot/http.go:200 +0x1aa
github.com/public-awesome/stakebot/bot.(*HTTPService).HandleCreateBotAccount(0xc0003b4000, 0x1b70860, 0xc001388380, 0xc001104100)
        /home/meow/Dev/Public-Awesome/stakebot/bot/http.go:124 +0x748
net/http.HandlerFunc.ServeHTTP(0xc00038ccc0, 0x1b70860, 0xc001388380, 0xc001104100)
        /usr/local/go/src/net/http/server.go:2042 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0004fcf00, 0x1b70860, 0xc001388380, 0xc001104100)
        /usr/local/go/src/net/http/server.go:2417 +0x1ad
github.com/public-awesome/stakebot/bot.(*HTTPService).ServeHTTP(0xc0003b4000, 0x1b70860, 0xc001388380, 0xc001104100)
        /home/meow/Dev/Public-Awesome/stakebot/bot/http.go:174 +0x4d
net/http.serverHandler.ServeHTTP(0xc0003b8000, 0x1b70860, 0xc001388380, 0xc001104100)
        /usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc001502140, 0x1b752e0, 0xc0000524c0)
        /usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2969 +0x36c
WARN[0059] can't find validator address to send coins   
ERRO[0059] error with multisend                          error="rpc error: code = NotFound desc = account stars128hqunynyku6muuwutpfx0gklhfrhjzn9fdnlc not found: key not found"
```

Looks like an address needs to updates?

On the frontend, chain queries (balance, apr, staking rewards) all seem to work, but txs needed typeUrls updated. After that Done with this PR: https://github.com/public-awesome/stargaze-app/pull/350

Some more work is likely needed with stakewatcher and the backend because even though my post transaction is successful from the frontend, it doesn't show up in the feed. Stakewatcher has 0 posts in its db.

**Comment by shanev** [comment]
> Ok, this does break some things (as was to be expected).
> 
> First thing seems to be on the bot side (when an account is created):

Stakebot and Stakewatcher have to have their imports updated to the point to the chain PR's version of the chain.

**Review by JakeHartnell — APPROVED** [review]
Looks great, just need to decide when we want to merge this and break things.

**Review by JakeHartnell — APPROVED** [review]

**Review by jhernandezb — APPROVED** [review]

**Pull request merged**
