### PR TITLE
Delete expired posts and upvotes, closes #75

### LINKED ISSUE #75: Delete expired posts and upvotes from chain

### PR DESCRIPTION
**Pull request by JakeHartnell**
Fixes a bug with Consensus Failure, see my comment on #75.

### CODE REVIEW

**Comment by JakeHartnell** [comment]
@shanev, do we even want to delete posts? If our blockchain is meant as a ledger of record... might it not be better to keep them and just add a property to posts that shows whether they are active or not?

**Comment by JakeHartnell** [comment]
If the answer is yes, I'm ok to merge this. I did test it quite a bit when I wrote it.

**Comment by shanev** [comment]
> @shanev, do we even want to delete posts? If our blockchain is meant as a ledger of record... might it not be better to keep them and just add a property to posts that shows whether they are active or not?

Good point. We should delete upvotes, but keep posts and add some metadata with voting results. Adding metadata can be another PR.

**Comment by JakeHartnell** [comment]
> Good point. We should delete upvotes, but keep posts and add some metadata with voting results. Adding metadata can be another PR.

Cool, we'll go with this for now.

**Pull request merged**
