### PR TITLE
reduce initial staked coins

### PR DESCRIPTION
**Pull request by jhernandezb**

### CODE REVIEW

**Comment by JakeHartnell** [comment]
Wasn't this just changed?

https://github.com/public-awesome/stakebird/pull/145/files

**Comment by jhernandezb** [comment]
Yes we need to revert it

**Comment by JakeHartnell** [comment]
Ok, figured. Thanks!

**Comment by jhernandezb** [comment]
Initially I thought we were increasing available tokens here https://github.com/public-awesome/stakebird/blob/master/cmd/staked/testnet.go#L215 but   it was actually matching available with staked tokens so it does have tokens but staked and 0 tokens for transfer.

**Pull request merged**
